#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Format and check SilverSat 2 command text (DS-50, DS-61).

Command text is "<app> <command> <arguments>", words separated by exactly
one space. Arguments are decimal integers (no leading zeros, '-' only for
negatives, never -0), true or false, or an enum value's name.

    python3 tools/command_text.py frame_manager set_entry_enabled nominal 3 false

prints the text if it is valid for the current definitions, ready to sign
with tools/sign_command.py. The rules here mirror the flight decoder
(include/silversat/cmd_route.h); the shared vectors in
tests/unit/command/vectors.yaml keep the two in step.
"""

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "messages" / "generator"))
sys.path.insert(0, str(REPO / "tools"))

import msggen  # noqa: E402
from sign_command import TEXT_MAX  # noqa: E402

WORDS_MAX = 16  # CMD_TEXT_WORDS_MAX

# The same order as enum cmd_route_result: the first that fails is reported.
RESULTS = ("ok", "bad_syntax", "unknown_app", "unknown_command", "bad_arg_count", "mode",
           "bad_arg", "publish_failed")

UNSIGNED_RE = re.compile(r"0|[1-9][0-9]{0,19}")
SIGNED_RE = re.compile(r"0|-?[1-9][0-9]{0,19}")


def load_dictionary(extra_app_dirs=()):
    """The command dictionary for the YAML in messages/ (DS-61)."""
    defs = msggen.load_definitions(REPO / "messages", extra_app_dirs)
    return msggen.command_dictionary(defs)


@dataclass
class Parsed:
    result: str
    app: str | None = None
    command: str | None = None
    bad_arg: int | None = None
    values: list = field(default_factory=list)


def _read(word, arg):
    """The value of one argument word, or None if it is not valid."""
    kind = arg["kind"]
    if kind in ("unsigned", "signed"):
        pattern = UNSIGNED_RE if kind == "unsigned" else SIGNED_RE
        if not pattern.fullmatch(word):
            return None
        value = int(word)
        return value if arg["min"] <= value <= arg["max"] else None
    if kind == "bool":
        return {"true": True, "false": False}.get(word)
    if kind == "enum":
        return word if word in arg["values"] else None
    raise ValueError(f"unknown argument kind {kind!r}")


def parse(dictionary, text, mode):
    """Check text exactly as the flight decoder does, in the current mode."""
    words = text.split(" ")
    if not text or "" in words or len(words) < 2 or len(words) > WORDS_MAX:
        return Parsed("bad_syntax")
    app = next((a for a in dictionary["apps"] if a["name"] == words[0]), None)
    if app is None:
        return Parsed("unknown_app")
    command = next((c for c in app["commands"] if c["name"] == words[1]), None)
    if command is None:
        return Parsed("unknown_command", app["name"])
    parsed = Parsed("ok", app["name"], command["name"])
    if len(words) - 2 != len(command["args"]):
        parsed.result = "bad_arg_count"
        return parsed
    if mode not in command["modes"]:
        parsed.result = "mode"
        return parsed
    for i, (word, arg) in enumerate(zip(words[2:], command["args"])):
        value = _read(word, arg)
        if value is None:
            parsed.result, parsed.bad_arg, parsed.values = "bad_arg", i, []
            return parsed
        parsed.values.append(value)
    return parsed


def _word(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def format_command(dictionary, app, command, *values):
    """Command text for app and command with the given argument values.
    Raises ValueError, naming the problem, if the flight decoder would reject
    it in every mode the command is allowed in."""
    text = " ".join([app, command] + [_word(v) for v in values])
    if len(text) > TEXT_MAX:
        raise ValueError(f"command text is longer than {TEXT_MAX} characters")
    modes = next((c["modes"] for a in dictionary["apps"] if a["name"] == app
                  for c in a["commands"] if c["name"] == command), dictionary["modes"][:1])
    parsed = parse(dictionary, text, modes[0])
    if parsed.result == "bad_arg":
        raise ValueError(f"{text!r}: argument {parsed.bad_arg + 1} is not valid")
    if parsed.result != "ok":
        raise ValueError(f"{text!r}: {parsed.result.replace('_', ' ')}")
    return text


# --- Shared vectors -------------------------------------------------------


def load_vectors(path):
    return yaml.safe_load(Path(path).read_text())["vectors"]


def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def c_vectors(vectors):
    """A C header of the vectors, for tests/unit/command."""
    out = ["/* GENERATED by tools/command_text.py --c-vectors. Do not edit. */", "",
           "#include <stdint.h>", "", '#include "msg/common.h"',
           '#include "silversat/cmd_route.h"', "",
           "struct route_vector {", "\tconst char *text;", "\tuint8_t mode;",
           "\tenum cmd_route_result result;", "\tuint8_t bad_arg;", "};", "",
           "static const struct route_vector route_vectors[] = {"]
    for v in vectors:
        out.append(f'\t{{"{c_escape(v["text"])}", MODE_{v["mode"].upper()}, '
                   f'CMD_ROUTE_{v["result"].upper()}, {v.get("bad_arg", 0)}}},')
    out += ["};", ""]
    return "\n".join(out)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("words", nargs="*", help="app, command, and arguments")
    parser.add_argument("--extra-apps", type=Path, action="append", default=[],
                        metavar="DIR", help="a directory of test-only <app>.yaml files")
    parser.add_argument("--vectors", type=Path, help="shared vectors (YAML)")
    parser.add_argument("--c-vectors", type=Path, metavar="FILE",
                        help="write --vectors as a C header to FILE")
    args = parser.parse_args(argv)

    try:
        if args.c_vectors:
            if not args.vectors:
                parser.error("--c-vectors needs --vectors")
            args.c_vectors.parent.mkdir(parents=True, exist_ok=True)
            args.c_vectors.write_text(c_vectors(load_vectors(args.vectors)))
            return 0
        if len(args.words) < 2:
            parser.error("give the app, the command, and its arguments")
        dictionary = load_dictionary(args.extra_apps)
        print(format_command(dictionary, args.words[0], args.words[1], *args.words[2:]))
    except (ValueError, msggen.DefinitionError) as e:
        print(f"command_text: error: {e}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
