#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Write the command keys into a C header for command ingest (DS-54).

The build runs this with the key files named in Kconfig
(CONFIG_SS_CMD_KEY_FILE_SLOT0 and _SLOT1). By default those are the
published test keys in tools/. A flight build points them at files written
from CI secrets and passes --flight, which refuses any published test key.

    python3 tools/key_header.py --slot0 KEYFILE --slot1 KEYFILE --out cmd_keys.h [--flight]

The header holds key material. It is written into the build directory and
must never be committed.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from sign_command import load_key  # noqa: E402

TOOLS = Path(__file__).parent
PUBLISHED_TEST_KEYS = (TOOLS / "test_key.txt", TOOLS / "test_key_slot1.txt")


def check_keys(keys, flight):
    """Raise ValueError if the keys can't be used together, or in flight."""
    if keys[0] == keys[1]:
        raise ValueError("both key slots have the same key; rotation would change nothing")
    if flight:
        published = {load_key(p) for p in PUBLISHED_TEST_KEYS}
        for slot, key in enumerate(keys):
            if key in published:
                raise ValueError(
                    f"slot {slot} is a published test key, which a flight build must "
                    "never use (DS-54)")


def header(keys, sources):
    lines = [
        "/*",
        " * GENERATED by tools/key_header.py. Do not edit, and never commit:",
        " * this file holds key material (DS-54).",
        " *",
    ]
    lines += [f" *   slot {slot}: {src}" for slot, src in enumerate(sources)]
    lines += [" */", "", "#include <stdint.h>", "",
              "static const uint8_t cmd_keys[2][32] = {"]
    for key in keys:
        lines.append("\t{" + ", ".join(f"0x{b:02x}" for b in key) + "},")
    lines += ["};", ""]
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--slot0", type=Path, required=True, help="key file for slot 0")
    parser.add_argument("--slot1", type=Path, required=True, help="key file for slot 1")
    parser.add_argument("--out", type=Path, required=True, help="header to write")
    parser.add_argument("--flight", action="store_true",
                        help="refuse the published test keys")
    args = parser.parse_args(argv)

    try:
        keys = [load_key(args.slot0), load_key(args.slot1)]
        check_keys(keys, args.flight)
    except (OSError, ValueError) as e:
        print(f"key_header: error: {e}", file=sys.stderr)
        return 1
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(header(keys, [args.slot0.name, args.slot1.name]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
