#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Sign SilverSat 2 ground commands (DS-52, DS-53).

A signed command is printable ASCII:

    <tag: 64 hex><salt: 16 hex><counter: 16 hex><command text>

The tag is keyed BLAKE2s over everything after it. The salt is 8 random
bytes per command; the counter is a 64-bit value, epoch milliseconds by
default, written as 16 lowercase hex digits.

    python3 tools/sign_command.py "noop"
    python3 tools/sign_command.py --counter 42 --key-file tools/test_key.txt "noop"

The default key is the published test key. It cannot command the flight
vehicle (DS-54).

The ground station uses sign(); the flight software's tests use this script
to generate their test vectors (--c-vectors), so the satellite is checked
against the same code the ground will use.
"""

import argparse
import hashlib
import secrets
import sys
import time
from pathlib import Path

KEY_LEN = 32
TAG_LEN = 32
SALT_LEN = 8
COUNTER_MAX = 2**64 - 1
PACKET_MAX = 255                      # whole packets stay under 256 bytes (DS-66)
HEADER_CHARS = 2 * (TAG_LEN + SALT_LEN + 8)
TEXT_MAX = PACKET_MAX - HEADER_CHARS  # 159

TEST_KEY_FILE = Path(__file__).parent / "test_key.txt"
TEST_KEY_FILES = {"slot0": TEST_KEY_FILE, "slot1": Path(__file__).parent / "test_key_slot1.txt"}


def load_key(path):
    """A 32-byte key from a file of hex, ignoring '#' comment lines."""
    lines = [ln.strip() for ln in Path(path).read_text().splitlines()]
    key = bytes.fromhex("".join(ln for ln in lines if ln and not ln.startswith("#")))
    if len(key) != KEY_LEN:
        raise ValueError(f"{path}: key must be {KEY_LEN} bytes, got {len(key)}")
    return key


def sign(command, key, counter, salt=None):
    """Return the signed packet for command text, as a str."""
    if not 1 <= len(command) <= TEXT_MAX:
        raise ValueError(f"command text must be 1 to {TEXT_MAX} characters")
    if not all(" " <= c <= "~" for c in command):
        raise ValueError("command text must be printable ASCII")
    if not 0 <= counter <= COUNTER_MAX:
        raise ValueError("counter must fit in 64 bits")
    if salt is None:
        salt = secrets.token_bytes(SALT_LEN)
    if len(salt) != SALT_LEN:
        raise ValueError(f"salt must be {SALT_LEN} bytes")

    signed = salt.hex() + f"{counter:016x}" + command
    tag = hashlib.blake2s(signed.encode("ascii"), key=key, digest_size=TAG_LEN)
    return tag.hexdigest() + signed


# The ground refuses to send a counter further ahead of its own clock than
# this (DS-53), so a mistake can't push the satellite's floor far ahead.
FUTURE_MARGIN_MS = 24 * 60 * 60 * 1000


def now_ms():
    return time.time_ns() // 1_000_000


def default_counter(last=0):
    """The larger of now in epoch milliseconds and last + 1 (DS-53)."""
    return max(now_ms(), last + 1)


def check_not_too_far_ahead(counter, now=None):
    """Raise ValueError if counter is more than a day ahead of the clock."""
    now = now_ms() if now is None else now
    if counter > now + FUTURE_MARGIN_MS:
        raise ValueError(
            f"counter {counter} is more than a day ahead of this clock ({now}); "
            "check its units, or use --allow-future if it is deliberate")


# --- C test vectors --------------------------------------------------------

# Fixed inputs, so the vectors are the same on every build.
VECTOR_SALT = bytes(range(1, SALT_LEN + 1))
VECTORS = [
    ("short", "noop", 1),
    ("typical", "frame_manager set_entry_enabled 1 3 0", 1_790_000_000_000),
    ("counter_max", "noop", COUNTER_MAX),
    ("longest", "x" * TEXT_MAX, 2),
    ("spaces_and_symbols", "set ~!@#$%^&*()_+-={}[]|:;'<>,.?/", 3),
]


def c_vectors(key):
    """A C header of signed packets, for tests/unit/command."""
    out = [
        "/* GENERATED by tools/sign_command.py --c-vectors. Do not edit. */",
        "",
        "#include <stdint.h>",
        "",
        "struct signed_vector {",
        "\tconst char *name;",
        "\tconst char *packet;",
        "\tconst char *text;",
        "\tuint64_t counter;",
        "};",
        "",
        "static const uint8_t vector_key[] = {",
        "\t" + ", ".join(f"0x{b:02x}" for b in key) + ",",
        "};",
        "",
        "static const uint8_t vector_salt[] = {",
        "\t" + ", ".join(f"0x{b:02x}" for b in VECTOR_SALT) + ",",
        "};",
        "",
        "static const struct signed_vector signed_vectors[] = {",
    ]
    for name, text, counter in VECTORS:
        packet = sign(text, key, counter, VECTOR_SALT)
        out.append(f'\t{{"{name}", "{c_escape(packet)}", "{c_escape(text)}", '
                   f"0x{counter:016x}ULL}},")
    out += ["};", ""]
    return "\n".join(out)


def c_packets(spec_path):
    """A C header of named packets from a YAML list, for app tests.

    Each entry has name, text, counter, and key (slot0 or slot1, the
    published test keys). Packets use the fixed vector salt, so the header
    is the same on every build.
    """
    import yaml

    entries = yaml.safe_load(Path(spec_path).read_text())["packets"]
    keys = {name: load_key(path) for name, path in TEST_KEY_FILES.items()}
    out = ["/* GENERATED by tools/sign_command.py --c-packets. Do not edit. */", ""]
    for e in entries:
        packet = sign(e["text"], keys[e["key"]], e["counter"], VECTOR_SALT)
        out.append(f"/* {e['key']}, counter {e['counter']}: {e['text']} */")
        out.append(f'#define PKT_{e["name"].upper()} "{c_escape(packet)}"')
        out.append(f"#define PKT_{e['name'].upper()}_COUNTER 0x{e['counter']:016x}ULL")
        out.append("")
    return "\n".join(out)


def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("command", nargs="?", help="command text to sign")
    parser.add_argument("--key-file", type=Path, default=TEST_KEY_FILE,
                        help="file of 64 hex digits (default: the published test key)")
    parser.add_argument("--counter", type=int, help="counter (default: epoch milliseconds)")
    parser.add_argument("--allow-future", action="store_true",
                        help="allow a counter more than a day ahead of this clock")
    parser.add_argument("--c-vectors", type=Path, metavar="FILE",
                        help="write C test vectors to FILE instead of signing")
    parser.add_argument("--c-packets", nargs=2, type=Path, metavar=("SPEC", "FILE"),
                        help="sign the packets listed in SPEC (YAML) into a C header FILE")
    args = parser.parse_args(argv)

    try:
        key = load_key(args.key_file)
        if args.c_vectors:
            args.c_vectors.parent.mkdir(parents=True, exist_ok=True)
            args.c_vectors.write_text(c_vectors(key))
            return 0
        if args.c_packets:
            spec, out = args.c_packets
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(c_packets(spec))
            return 0
        if args.command is None:
            parser.error("give the command text to sign")
        counter = default_counter() if args.counter is None else args.counter
        if not args.allow_future:
            check_not_too_far_ahead(counter)
        print(sign(args.command, key, counter))
    except ValueError as e:
        print(f"sign_command: error: {e}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
