#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Decode SilverSat 2 downlink packets (DS-61, DS-64).

Every downlink packet starts with a printable kind byte:

    'A', 'N'  command replies, as text: "ACK <counter> ok", "NAK <counter> replay"
    'H'       housekeeping: 'H', app id, MET (8 bytes), then the app's
              housekeeping fields, little-endian, packed in YAML order

The housekeeping layouts come from the same YAML as the flight encoders
(include/silversat/tlm_encode.h), through the generator's dictionary.

    python3 tools/telemetry.py --vectors VECTORS.yaml --c-vectors OUT.h

writes housekeeping vectors as a C header for tests/unit/libs.
"""

import argparse
import struct
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "tools"))

import command_text  # noqa: E402

KIND_HK = ord("H")
REPLY_KINDS = (ord("A"), ord("N"))
HK_HEADER_LEN = 10

FLOAT_FORMATS = {"float32": "<f", "float64": "<d"}


def load_dictionary(extra_app_dirs=()):
    return command_text.load_dictionary(extra_app_dirs)


def _app(dictionary, key, value):
    app = next((a for a in dictionary["apps"] if a[key] == value), None)
    if app is None:
        raise ValueError(f"no app with {key} {value!r}")
    return app


def _decode_field(field, data):
    raw = data[field["offset"]:field["offset"] + field["size"]]
    kind = field["type"]
    if "values" in field:
        number = int.from_bytes(raw, "little")
        return next((v["name"] for v in field["values"] if v["value"] == number), number)
    if kind == "bool":
        return raw[0] != 0
    if kind in FLOAT_FORMATS:
        return struct.unpack(FLOAT_FORMATS[kind], raw)[0]
    return int.from_bytes(raw, "little", signed=kind.startswith("int"))


def _encode_field(field, value):
    kind = field["type"]
    if "values" in field:
        if isinstance(value, str):
            value = next(v["value"] for v in field["values"] if v["name"] == value)
        return value.to_bytes(field["size"], "little")
    if kind == "bool":
        return bytes([1 if value else 0])
    if kind in FLOAT_FORMATS:
        return struct.pack(FLOAT_FORMATS[kind], value)
    return value.to_bytes(field["size"], "little", signed=kind.startswith("int"))


def decode(dictionary, payload):
    """One downlink packet, as a dict with "kind": "reply" or "hk"."""
    if not payload:
        raise ValueError("empty packet")
    if payload[0] in REPLY_KINDS:
        return {"kind": "reply", "text": payload.decode("ascii")}
    if payload[0] != KIND_HK:
        raise ValueError(f"unknown packet kind {payload[0]:#04x}")
    if len(payload) < HK_HEADER_LEN:
        raise ValueError("housekeeping packet too short")
    app = _app(dictionary, "id", payload[1])
    hk = app["housekeeping"]
    data = payload[HK_HEADER_LEN:]
    if len(data) != hk["size"]:
        raise ValueError(f"{app['name']} housekeeping is {hk['size']} bytes, got {len(data)}")
    return {
        "kind": "hk",
        "app": app["name"],
        "met_ms": int.from_bytes(payload[2:HK_HEADER_LEN], "little", signed=True),
        "fields": {f["name"]: _decode_field(f, data) for f in hk["fields"]},
    }


def encode_hk(dictionary, app_name, met_ms, values):
    """The 'H' packet the flight encoder sends for these values."""
    app = _app(dictionary, "name", app_name)
    body = b"".join(_encode_field(f, values[f["name"]]) for f in app["housekeeping"]["fields"])
    return bytes([KIND_HK, app["id"]]) + met_ms.to_bytes(8, "little", signed=True) + body


# --- Shared vectors -------------------------------------------------------


def _c_value(field, value):
    if "values" in field:
        return str(next(v["value"] for v in field["values"] if v["name"] == value))
    if field["type"] == "bool":
        return "true" if value else "false"
    if field["type"] == "float32":
        return f"{float(value)!r}f"
    if field["type"] == "float64":
        return repr(float(value))
    if field["type"] == "int64" and value == -2**63:
        return "INT64_MIN"
    if field["type"] == "uint64":
        return f"{value}ULL"
    if field["type"] == "int64":
        return f"{value}LL"
    return str(value)


def c_vectors(dictionary, path):
    """Housekeeping vectors as a C header: each a struct to publish and the
    packet the flight encoder must produce."""
    import yaml

    vectors = yaml.safe_load(Path(path).read_text())["vectors"]
    out = ["/* GENERATED by tools/telemetry.py --c-vectors. Do not edit. */", "",
           "#include <stdbool.h>", "#include <stdint.h>", ""]
    rows = []
    for i, v in enumerate(vectors):
        app = _app(dictionary, "name", v["app"])
        fields = app["housekeeping"]["fields"]
        init = ", ".join(f".{f['name']} = {_c_value(f, v['values'][f['name']])}" for f in fields)
        packet = encode_hk(dictionary, v["app"], v["met_ms"], v["values"])
        out.append(f"static const struct {v['app']}_hk hk_{i} = {{{init}}};")
        out.append(f"static const uint8_t packet_{i}[] = "
                   f"{{{', '.join(f'0x{b:02x}' for b in packet)}}};")
        rows.append(f'\t{{"{v["name"]}", &hk_{i}, {v["met_ms"]}LL, packet_{i}, sizeof(packet_{i})}},')
    out += ["", "struct hk_vector {", "\tconst char *name;", f"\tconst struct {vectors[0]['app']}_hk *hk;",
            "\tint64_t met_ms;", "\tconst uint8_t *packet;", "\tsize_t len;", "};", "",
            "static const struct hk_vector hk_vectors[] = {"] + rows + ["};", ""]
    return "\n".join(out)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--vectors", type=Path, required=True,
                        help="housekeeping vectors (YAML); all for one app")
    parser.add_argument("--c-vectors", type=Path, required=True, metavar="FILE")
    parser.add_argument("--extra-apps", type=Path, action="append", default=[],
                        metavar="DIR", help="a directory of test-only <app>.yaml files")
    args = parser.parse_args(argv)
    dictionary = load_dictionary(args.extra_apps)
    args.c_vectors.parent.mkdir(parents=True, exist_ok=True)
    args.c_vectors.write_text(c_vectors(dictionary, args.vectors))
    return 0


if __name__ == "__main__":
    sys.exit(main())
